netty:
  start: 127.0.0.1
  host: 127.0.0.1
  port: 8531
  enable: true

rabbitmq:
  host: 127.0.0.1
  port: 5672
  username: tlcloud
  password: tloaproj

#rabbitmq连接参数
spring:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: tlcloud
    password: tloaproj
    # 开启发送确认
    publisher-confirms: true
    # 开启发送失败退回
    publisher-returns: true
    # 开启ACK
    listener:
      direct:
        acknowledge-mode: manual
      simple:
        acknowledge-mode: manual