redis:
    ip: 127.0.0.1
    port: 6379
    password: 
    timeout: 2000
    max:
        total: 200 #最大连接数
        idle: 10 #最大空闲数
    min:
        idle: 2 #最小空闲数
    test:
        borrow: true #从jedis连接池获取连接时，校验并返回可用的连接
        return: false #把连接放回jedis连接池时，校验并返回可用的连接

# 使用redis实现分布式session共享
spring:
    redisson:
        address: 127.0.0.1:6379
    redis:
       database: 0
       host: 127.0.0.1
       port: 6379
       password: 
       timeout: 20000
       pool:
           max-active: 200
           max-wait: -1
           max-idle: 10
           min-idle: 2
    session:
        store-type: redis